version: '3'

## memochat-server-local과 같은 외부네트쿼읔 설정
networks:
  memochat-server-network:
    driver: bridge
    external: true

services:
  pg-developement:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'memochat'
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: 'memochat-dev'

    ## memochat-server-local과 같은 외부네트쿼읔 설정
    networks:
      - memochat-server-network
